version: '3'

services:
  ai-customer-behavior:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
      - ./reports:/app/reports
    environment:
      - FLASK_ENV=development